const today = new Date('2026-10-05T00:00:00');
const units = [
{id:'A-01',area:125,type:'Retail',tenant:'PT Nusantara Food',company:'PT Nusantara Food Indonesia',start:'2026-01-01',end:'2027-12-31',rent:25000000,payment:'paid',due:'2026-10-31',paidDate:'2026-10-02',pic:'Budi Santoso',contact:'0812-1111-2222',x:105,y:92,w:180,h:110},
{id:'A-02',area:90,type:'Retail',tenant:'CV Kopi Kita',company:'CV Kopi Kita',start:'2026-02-01',end:'2026-11-30',rent:18000000,payment:'paid',due:'2026-10-31',paidDate:'2026-10-01',pic:'Rina Putri',contact:'0813-2222-3333',x:300,y:92,w:150,h:110},
{id:'A-03',area:110,type:'Office',tenant:'PT Satu Data',company:'PT Satu Data Indonesia',start:'2026-03-01',end:'2026-12-15',rent:22000000,payment:'overdue',due:'2026-10-05',paidDate:'-',pic:'Andi Wijaya',contact:'0814-3333-4444',x:465,y:92,w:170,h:110},
{id:'A-04',area:75,type:'Retail',tenant:'PT Urban Mart',company:'PT Urban Mart',start:'2026-01-15',end:'2027-06-30',rent:15000000,payment:'paid',due:'2026-10-31',paidDate:'2026-10-03',pic:'Dewi Lestari',contact:'0815-4444-5555',x:650,y:92,w:155,h:110},
{id:'A-05',area:140,type:'Office',tenant:'PT Geospasial',company:'PT Geospasial Nusantara',start:'2026-01-01',end:'2026-12-20',rent:28000000,payment:'unpaid',due:'2026-10-10',paidDate:'-',pic:'Fajar Rahman',contact:'0816-5555-6666',x:105,y:300,w:190,h:125},
{id:'A-06',area:82,type:'Retail',tenant:'PT Fresh Corner',company:'PT Fresh Corner',start:'2026-04-01',end:'2027-03-31',rent:16000000,payment:'paid',due:'2026-10-31',paidDate:'2026-10-04',pic:'Sari Ananda',contact:'0817-6666-7777',x:310,y:300,w:140,h:125},
{id:'A-07',area:100,type:'Office',tenant:'PT Arunika',company:'PT Arunika Teknologi',start:'2026-01-01',end:'2026-10-25',rent:21000000,payment:'paid',due:'2026-10-31',paidDate:'2026-10-01',pic:'Yoga Pratama',contact:'0818-7777-8888',x:465,y:300,w:145,h:125},
{id:'A-08',area:95,type:'Retail',tenant:'PT Ruang Rasa',company:'PT Ruang Rasa',start:'2026-05-01',end:'2027-04-30',rent:19000000,payment:'paid',due:'2026-10-31',paidDate:'2026-10-02',pic:'Maya Sari',contact:'0819-8888-9999',x:625,y:300,w:180,h:125},
{id:'A-09',area:130,type:'Office',tenant:'PT Cipta Karya',company:'PT Cipta Karya',start:'2026-01-01',end:'2028-01-31',rent:27000000,payment:'paid',due:'2026-10-31',paidDate:'2026-10-01',pic:'Rizky Akbar',contact:'0821-9999-1111',x:105,y:465,w:160,h:80},
{id:'A-10',area:78,type:'Retail',tenant:'PT Bumi Sehat',company:'PT Bumi Sehat',start:'2026-06-01',end:'2027-05-31',rent:15500000,payment:'overdue',due:'2026-10-01',paidDate:'-',pic:'Nadia Putri',contact:'0822-1111-3333',x:280,y:465,w:175,h:80},
{id:'A-11',area:105,type:'Office',tenant:'PT Data Prima',company:'PT Data Prima',start:'2026-01-01',end:'2027-12-31',rent:21500000,payment:'paid',due:'2026-10-31',paidDate:'2026-10-02',pic:'Hendra Yusuf',contact:'0823-2222-4444',x:470,y:465,w:160,h:80},
{id:'A-12',area:88,type:'Retail',tenant:null,company:null,start:null,end:null,rent:0,payment:'vacant',due:'-',paidDate:'-',pic:'-',contact:'-',x:645,y:465,w:160,h:80}
];
const histories={
'A-01':[['Sep 2026','25 jt','02 Sep 2026','paid'],['Aug 2026','25 jt','02 Aug 2026','paid'],['Jul 2026','25 jt','01 Jul 2026','paid']],
'A-03':[['Oct 2026','22 jt','-','overdue'],['Sep 2026','22 jt','03 Sep 2026','paid'],['Aug 2026','22 jt','02 Aug 2026','paid']],
'A-05':[['Oct 2026','28 jt','-','unpaid'],['Sep 2026','28 jt','02 Sep 2026','paid'],['Aug 2026','28 jt','01 Aug 2026','paid']],
'A-10':[['Oct 2026','15,5 jt','-','overdue'],['Sep 2026','15,5 jt','01 Sep 2026','paid'],['Aug 2026','15,5 jt','02 Aug 2026','paid']]
};
let labelsVisible=true, zoom=1, selectedId=null;
const floorMap=document.getElementById('floorMap');
function color(u){if(u.payment==='overdue')return '#d96666';if(u.payment==='unpaid'||leaseState(u)==='expiring')return '#e4b63b';if(u.payment==='vacant')return '#6d9fdb';return '#49ad78'}
function daysRemaining(end){return end?Math.ceil((new Date(end)-today)/86400000):null}
function leaseState(u){const d=daysRemaining(u.end);if(!u.end)return 'vacant';if(d<0)return 'expired';if(d<=90)return 'expiring';return 'active'}
function statusText(u){return !u.tenant?'KOSONG':u.payment==='overdue'?'OVERDUE':u.payment==='unpaid'?'BELUM BAYAR':leaseState(u)==='expiring'?'KONTRAK SEGERA HABIS':'LUNAS'}
function money(n){return n?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n):'-'}
function dateFmt(s){return s&&s!=='-'?new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s)):'-'}
function initials(name){return name?name.split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase():'--'}
function buildSvg(){
 let svg=`<svg class="floor-svg" viewBox="0 0 920 560" xmlns="http://www.w3.org/2000/svg" aria-label="Denah Gedung A lantai 1">
 <rect x="0" y="0" width="920" height="560" rx="24" fill="#f8fafb"/>
 <path class="wall" d="M55 55H835V505H55V390H85V210H55Z"/>
 <path class="corridor" d="M75 238H820V285H75Z"/><path class="corridor" d="M270 75V485H315V75Z"/>
 <path class="corridor" d="M600 75V485H635V75Z"/>
 <path class="lobby" d="M390 238H545V285H390Z"/><text x="467" y="267" class="room-text" text-anchor="middle">KORIDOR UTAMA</text>
 <rect class="stairs" x="78" y="335" width="45" height="50" rx="4"/><path class="stair-line" d="M84 344h33M84 353h33M84 362h33M84 371h33"/><text x="100" y="410" class="room-text" text-anchor="middle">TANGGA</text>
 <rect class="stairs" x="770" y="335" width="45" height="50" rx="4"/><path class="stair-line" d="M776 344h33M776 353h33M776 362h33M776 371h33"/><text x="792" y="410" class="room-text" text-anchor="middle">TANGGA</text>
 <rect x="342" y="105" width="205" height="85" rx="14" fill="#eef2f5" stroke="#d2dae1"/><text x="444" y="135" class="site-label" text-anchor="middle">AREA LOBBY</text><text x="444" y="151" class="room-text" text-anchor="middle">RESEPSIONIS / WAITING</text>
 <text x="70" y="43" class="site-label">GEDUNG A • LANTAI 1</text>`;
 units.forEach(u=>{svg+=`<g class="unit-group" data-id="${u.id}"><rect class="unit" id="unit-${u.id}" x="${u.x}" y="${u.y}" width="${u.w}" height="${u.h}" rx="8" fill="${color(u)}" fill-opacity=".82"/><text class="unit-label" x="${u.x+u.w/2}" y="${u.y+u.h/2-2}">${u.id}</text><text class="unit-sub" x="${u.x+u.w/2}" y="${u.y+u.h/2+14}">${u.tenant?u.tenant.replace('PT ','').replace('CV ','').slice(0,18):'UNIT KOSONG'}</text></g>`});
 svg+='</svg>';floorMap.innerHTML=svg;
 document.querySelectorAll('.unit-group').forEach(g=>{g.addEventListener('click',()=>openDetail(g.dataset.id));g.addEventListener('mouseenter',()=>{if(selectedId!==g.dataset.id)document.getElementById('unit-'+g.dataset.id).classList.add('active-highlight')});g.addEventListener('mouseleave',()=>{if(selectedId!==g.dataset.id)document.getElementById('unit-'+g.dataset.id).classList.remove('active-highlight')})});
}
function filtered(){const payment=document.getElementById('paymentFilter').value,lease=document.getElementById('leaseFilter').value,q=document.getElementById('searchInput').value.toLowerCase();const allowed=[...document.querySelectorAll('.unitFilter:checked')].map(x=>x.value);return units.filter(u=>allowed.includes(u.tenant?'occupied':'vacant')&&(payment==='all'||u.payment===payment)&&(lease==='all'||leaseState(u)===lease)&&(!q||u.id.toLowerCase().includes(q)||(u.tenant||'').toLowerCase().includes(q)))}
function refresh(){const vis=filtered();units.forEach(u=>{const el=document.getElementById('unit-'+u.id);const show=vis.includes(u);el.classList.toggle('hidden',!show)});renderList(vis);updateDashboard();document.getElementById('resultText').textContent=`${vis.length} dari ${units.length} unit ditampilkan`;}
function renderList(items){const el=document.getElementById('unitList');el.innerHTML='';items.forEach(u=>{const b=document.createElement('button');b.className='unit-item';const cls=u.payment==='overdue'?'overdue':u.payment==='unpaid'?'unpaid':u.payment==='vacant'?'vacant':'paid';b.innerHTML=`<span><b>${u.id}</b><small>${u.tenant||'Unit kosong'} • ${u.area} m²</small></span><span class="mini-status ${cls}">${statusText(u)}</span>`;b.onclick=()=>openDetail(u.id);el.appendChild(b)})}
function updateDashboard(){const occupied=units.filter(u=>u.tenant).length,exp=units.filter(u=>leaseState(u)==='expiring').length,over=units.filter(u=>u.payment==='overdue').length;document.getElementById('totalUnits').textContent=units.length;document.getElementById('occupied').textContent=occupied;document.getElementById('occupancyPct').textContent=Math.round(occupied/units.length*100)+'% occupancy';document.getElementById('expiring').textContent=exp;document.getElementById('overdue').textContent=over;const a=document.getElementById('attention');a.innerHTML='';units.filter(u=>u.payment==='overdue'||u.payment==='unpaid'||leaseState(u)==='expiring').forEach(u=>{const d=document.createElement('div');d.className='attention-item';d.innerHTML=`<b>${u.id} — ${u.tenant||'Kosong'}</b><small>${u.payment==='overdue'?'Tunggakan pembayaran':u.payment==='unpaid'?'Belum bayar':'Kontrak segera berakhir'}</small>`;d.onclick=()=>openDetail(u.id);a.appendChild(d)})}
function openDetail(id){const u=units.find(x=>x.id===id);if(!u)return;selectedId=id;document.querySelectorAll('.active-highlight').forEach(e=>e.classList.remove('active-highlight'));document.getElementById('unit-'+id).classList.add('active-highlight');document.getElementById('detailCode').textContent=`GEDUNG A / LANTAI 1 / ${u.id}`;document.getElementById('detailUnit').textContent=u.id;const st=document.getElementById('detailStatus');st.className='status-pill';st.textContent=statusText(u);if(!u.tenant)st.classList.add('vacant');else if(u.payment==='overdue')st.classList.add('bad');else if(leaseState(u)==='expiring')st.classList.add('warn');document.getElementById('avatar').textContent=initials(u.tenant);document.getElementById('detailTenant').textContent=u.tenant||'Belum ada tenant';document.getElementById('detailCompany').textContent=u.company||'Unit tersedia untuk disewa';document.getElementById('detailArea').textContent=u.area+' m²';document.getElementById('detailType').textContent=u.type;document.getElementById('detailStart').textContent=dateFmt(u.start);document.getElementById('detailEnd').textContent=dateFmt(u.end);const rem=daysRemaining(u.end);document.getElementById('detailRemaining').textContent=rem===null?'-':rem<0?'Lewat '+Math.abs(rem)+' hari':rem+' hari';document.getElementById('detailRent').textContent=money(u.rent);document.getElementById('detailPayment').textContent=u.payment==='paid'?'LUNAS':u.payment==='overdue'?'OVERDUE':u.payment==='unpaid'?'BELUM BAYAR':'-';document.getElementById('detailDue').textContent=dateFmt(u.due);document.getElementById('detailPaidDate').textContent=dateFmt(u.paidDate);document.getElementById('detailPic').textContent=u.pic;document.getElementById('detailContact').textContent=u.contact;document.getElementById('detailPanel').classList.add('show')}
function closeDetail(){document.getElementById('detailPanel').classList.remove('show');selectedId=null;document.querySelectorAll('.active-highlight').forEach(e=>e.classList.remove('active-highlight'))}
function setZoom(z){zoom=Math.max(.65,Math.min(1.45,z));floorMap.style.transform=`translate(-50%,-50%) scale(${zoom})`;document.getElementById('zoomValue').textContent=Math.round(zoom*100)+'%'}
document.getElementById('zoomIn').onclick=()=>setZoom(zoom+.1);document.getElementById('zoomOut').onclick=()=>setZoom(zoom-.1);document.getElementById('zoomFit').onclick=()=>setZoom(1);document.getElementById('toggleLabels').onclick=()=>{labelsVisible=!labelsVisible;document.querySelectorAll('.unit-label,.unit-sub').forEach(e=>e.style.display=labelsVisible?'':'none')};document.getElementById('closeDetail').onclick=closeDetail;
document.getElementById('resetBtn').onclick=()=>{document.getElementById('searchInput').value='';document.getElementById('paymentFilter').value='all';document.getElementById('leaseFilter').value='all';document.querySelectorAll('.unitFilter').forEach(x=>x.checked=true);closeDetail();setZoom(1);refresh()};
['paymentFilter','leaseFilter','searchInput'].forEach(id=>document.getElementById(id).addEventListener('input',refresh));document.querySelectorAll('.unitFilter').forEach(x=>x.addEventListener('change',refresh));document.getElementById('clearSearch').onclick=()=>{document.getElementById('searchInput').value='';refresh()};
document.getElementById('historyBtn').onclick=()=>{const id=document.getElementById('detailUnit').textContent,rows=histories[id]||[['Okt 2026','-','-','-'],['Sep 2026','-','-','-']];document.getElementById('modalTitle').textContent=`Riwayat Pembayaran — ${id}`;document.getElementById('modalBody').innerHTML=`<table class="history-table"><thead><tr><th>Periode</th><th>Tagihan</th><th>Tgl. bayar</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td><span class="badge ${r[3]}">${r[3].toUpperCase()}</span></td></tr>`).join('')}</tbody></table>`;document.getElementById('modalBg').classList.add('show')};
document.getElementById('editBtn').onclick=()=>{document.getElementById('modalTitle').textContent='Edit Data Tenant';document.getElementById('modalBody').innerHTML=`<p style="font-size:10px;line-height:1.7;color:#68727f">Ini masih demo. Pada versi produksi, form ini dapat tersambung ke API/database untuk mengubah tenant, kontrak, tarif sewa, PIC, dokumen, dan status pembayaran.</p><button class="primary-action" onclick="document.getElementById('modalBg').classList.remove('show')">Tutup</button>`;document.getElementById('modalBg').classList.add('show')};
document.getElementById('howBtn').onclick=()=>{document.getElementById('modalTitle').textContent='Bagaimana versi SVG ini bekerja?';document.getElementById('modalBody').innerHTML=`<div style="font-size:10px;line-height:1.8;color:#68727f"><b>1. Denah</b> dibuat sebagai SVG vector sehingga bentuk ruang tidak harus kotak.<br><b>2. Setiap unit</b> adalah elemen SVG dengan Unit ID unik.<br><b>3. Data tenant</b> masih berupa array JavaScript dummy.<br><b>4. Klik unit</b> membaca Unit ID lalu membuka panel detail.<br><b>5. Warna unit</b> dihitung dari status pembayaran dan kontrak.<br><b>6. Produksi</b> nantinya dapat mengganti array dummy dengan API + PostgreSQL/PostGIS tanpa mengubah konsep interaksinya.</div>`;document.getElementById('modalBg').classList.add('show')};
document.getElementById('closeModal').onclick=()=>document.getElementById('modalBg').classList.remove('show');document.getElementById('modalBg').onclick=e=>{if(e.target.id==='modalBg')document.getElementById('modalBg').classList.remove('show')};
// scroll wheel zoom, tetap offline
const viewport=document.getElementById('mapViewport');viewport.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom+(e.deltaY<0?.08:-.08))},{passive:false});
buildSvg();refresh();
